/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppMoviesMovieIdRouteImport } from './routes/_app/movies.$movieId'
import { Route as AppMoviesMovieIdIndexRouteImport } from './routes/_app/movies.$movieId/index'
import { Route as AppMoviesMovieIdCastRouteImport } from './routes/_app/movies.$movieId/cast'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMoviesMovieIdRoute = AppMoviesMovieIdRouteImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => AppRoute,
} as any)
const AppMoviesMovieIdIndexRoute = AppMoviesMovieIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMoviesMovieIdRoute,
} as any)
const AppMoviesMovieIdCastRoute = AppMoviesMovieIdCastRouteImport.update({
  id: '/cast',
  path: '/cast',
  getParentRoute: () => AppMoviesMovieIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof AppHomeRoute
  '/search': typeof AppSearchRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/movies/$movieId': typeof AppMoviesMovieIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/movies/$movieId/cast': typeof AppMoviesMovieIdCastRoute
  '/movies/$movieId/': typeof AppMoviesMovieIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof AppHomeRoute
  '/search': typeof AppSearchRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/movies/$movieId/cast': typeof AppMoviesMovieIdCastRoute
  '/movies/$movieId': typeof AppMoviesMovieIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_app/search': typeof AppSearchRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/movies/$movieId': typeof AppMoviesMovieIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/movies/$movieId/cast': typeof AppMoviesMovieIdCastRoute
  '/_app/movies/$movieId/': typeof AppMoviesMovieIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/search'
    | '/login'
    | '/signup'
    | '/movies/$movieId'
    | '/api/auth/$'
    | '/movies/$movieId/cast'
    | '/movies/$movieId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/search'
    | '/login'
    | '/signup'
    | '/api/auth/$'
    | '/movies/$movieId/cast'
    | '/movies/$movieId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/home'
    | '/_app/search'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_app/movies/$movieId'
    | '/api/auth/$'
    | '/_app/movies/$movieId/cast'
    | '/_app/movies/$movieId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/movies/$movieId': {
      id: '/_app/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof AppMoviesMovieIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movies/$movieId/': {
      id: '/_app/movies/$movieId/'
      path: '/'
      fullPath: '/movies/$movieId/'
      preLoaderRoute: typeof AppMoviesMovieIdIndexRouteImport
      parentRoute: typeof AppMoviesMovieIdRoute
    }
    '/_app/movies/$movieId/cast': {
      id: '/_app/movies/$movieId/cast'
      path: '/cast'
      fullPath: '/movies/$movieId/cast'
      preLoaderRoute: typeof AppMoviesMovieIdCastRouteImport
      parentRoute: typeof AppMoviesMovieIdRoute
    }
  }
}

interface AppMoviesMovieIdRouteChildren {
  AppMoviesMovieIdCastRoute: typeof AppMoviesMovieIdCastRoute
  AppMoviesMovieIdIndexRoute: typeof AppMoviesMovieIdIndexRoute
}

const AppMoviesMovieIdRouteChildren: AppMoviesMovieIdRouteChildren = {
  AppMoviesMovieIdCastRoute: AppMoviesMovieIdCastRoute,
  AppMoviesMovieIdIndexRoute: AppMoviesMovieIdIndexRoute,
}

const AppMoviesMovieIdRouteWithChildren =
  AppMoviesMovieIdRoute._addFileChildren(AppMoviesMovieIdRouteChildren)

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppSearchRoute: typeof AppSearchRoute
  AppMoviesMovieIdRoute: typeof AppMoviesMovieIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppSearchRoute: AppSearchRoute,
  AppMoviesMovieIdRoute: AppMoviesMovieIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
